// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Spacer(Props) {
  var height = Props.height;
  var width = Props.width;
  var w = width !== undefined ? String(width) + "px" : "0px";
  var h = height !== undefined ? String(height) + "px" : "0px";
  return React.createElement("div", {
              style: {
                height: h,
                width: w
              }
            });
}

var make = Spacer;

exports.make = make;
/* react Not a pure module */
